### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by jbrewlet** [tapnair/DXFImporter#1]
Hey there. I was excited to find this. However, upon installing it and restarting an updated Fusion 360 it gives me this error below.

I'm running macOS Catalina 10.15.4

<img width="401" alt="Screen Shot 2020-04-28 at 10 03 38 AM" src="https://user-images.githubusercontent.com/5932085/80520312-1b774380-893e-11ea-8491-bd7d26e0e150.png">

**Comment by tapnair** [comment]
Hwey I just made a bunch of updates to the imports, should be more robust.  If you cloned the repo, note the "For developers" section in the readme.  You need to update the "apper" submodule.  Alternatively just download the distribution zip file from the link near the top of the Readme.
